FROM openjdk:17

ADD agrirouter-middleware-application/target/agrirouter-middleware.jar /opt/application/application.jar

RUN chmod 775 -R /opt/application && chown 1000:root -R /opt/application

USER 1000
EXPOSE 8080

WORKDIR /opt/application

ENV JAVA_OPTS=""

CMD java $JAVA_OPTS -jar application.jar