= Agrirouter© Middleware

== Documentation

=== Swagger

The project provides a Swagger documentation and brings its own Swagger-UI that can be accessed using the following url:

http://your-path-to-the-middleware/swagger-ui/index.html

When running the project locally, the Swagger-UI can be found http://localhost:8080/swagger-ui/index.html[here].

== Development

=== Prerequisites for building and running the application

* Java 17
* Maven

=== Setting up the database for local development using `docker-compose`

To have a rapid start into developing, you can use the `docker compose` script located within the `dev` folder. The script created both of the necessary databases and after this you are ready to start the development.
In addition, there is a run configuration for IDEA with all environment variables set - ready, steady, go!

=== Environment variables

To run the application, the following environment variables have to be set.

|===
|Name |Description 

|`MONGODB_HOST` |Host for the MongoDB. 
|`MONGODB_PASSWORD` |Password for the MongoDB. 
|`MONGODB_PORT` |Port for the MongoDB. 
|`MONGODB_SCHEMA` |Schema / Database for the MongoDB. 
|`MONGODB_USER` |User for the MongoDB. 
|`MYSQL_HOST` |Host for the Maria DB / MySQL. 
|`MYSQL_PASSWORD` |Password for the Maria DB / MySQL. 
|`MYSQL_PORT` |Port for the Maria DB / MySQL. 
|`MYSQL_SCHEMA` |Schema / Database for the Maria DB / MySQL. 
|`MYSQL_USER` |User for the Maria DB / MySQL. 
|===

=== Authentication for the GitHub packages

To build the project from scratch you need to authenticate for GitHub packages. Please see the
following https://docs.github.com/en/packages/guides/configuring-apache-maven-for-use-with-github-packages[website]
for more details.

=== Run database

Within the `env/database` folder there is a shell script to build and run the database. Just run `build.sh` to create
and run a docker container.

=== Create and run the docker image

Creating the docker image is straight-forward.

* Build and install all the dependencies via `mvn clean install`.
* Run `spring-boot:build-image` to create the docker image within the module `agrirouter-middleware-application`.
* Run `docker run -it -p8080:8080 agrirouter-middleware-application:1.0-SNAPSHOT` to run the container locally.

=== Running the whole stack using docker-compose

You can run the whole required stack, including Mongo and MariaDB, using docker-compose.

* copy `.env.example` to `.env` (or run `./prepare-env.sh`, which sets secure passwords)
* edit `.env`:
* set `GITHUB_USER` and `GITHUB_TOKEN` to credentials from Github, the token only needs `read:packages` rights
* set all fields marked as "required" (not needed if `prepare-env` has been used)
* run (one of) the following commands:
* `docker-compose build`: builds the agrirouter-middleware sourcecode and packs it into a docker image
* `docker-compose up [-d]`: creates and starts all containers (agrirouter middleware, mongo and mysql) [in detached mode]
* `docker-compose stop`: stops the running containers
* `docker-compose down [-v]`: removes all containers, but keeps the volumes which hold the data [unless -v is specified]
* `docker-compose logs [-f]`: print the accumulated logs from all containers [and follow the output]

After the initialization of the databases is complete (the middleware container will restart multiple times
because the database is not available yet) and all containers are up, you can extract the generated tenant credentials from the logs:

----
docker-compose logs middleware | grep "Generated default" -B 2 -A 8
----