name: CI

on:
  pull_request:
  merge_group:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build-with-maven:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java Setup
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: corretto
      - name: Maven Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify --file pom.xml --settings ci/github-settings.xml
      - name: Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/target/surefire-reports/*.xml'
          detailed_summary: true
          include_passed: true