name: Docker CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build & push the Image
      uses: docker/build-push-action@v2
      with:
        push: false
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker build . --file .github/dockerfile --tag agrirouter-middleware:$(date +%s)
