name: Docker CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker build . --file .github/dockerfile --tag agrirouter-middleware:$(date +%s)
